_layouts/default.html
added google tag manager, with GA running in it
=> added google tag manager with google analytics running in it.

_layouts/default.html, _sass/header.scss
✨ Install Armory Button
⚔️ Ninja Moves
=> ✨ Knowledge Base header updates

_layouts/default.html, _sass/header.scss
- Fixes the dead button link for the Knowledge Base
=> 🙃 Button href to Learn More

_posts/1000-09-04-serverless.md
add a post about using jenkins to roll out faas stuff
=> feat(posts): add serverless post

_posts/1000-09-03-config-mgmt.md
add post about using ansible and other config management with spinnaker
=> feat(posts): add config management post

_posts/admin/2018-05-09-orca-flush-queue.md
document how diagnore and resolve slow orca perf
=> feat(orca): add orca admin post

_posts/admin/2018-05-01-travis-ci.md
after _actually_ configuring travis, i learned more
=> fix(travis): fix travis post

_layouts/default.html, _sass/header.scss
=> feat(layout): add github badge and link

_posts/pipelines/1000-07-18-github-artifact-trigger.md
add post on configuring github artifacts and webhooks
=> feat(artifacts/github): github artifact post

_posts/pipelines/1000-07-18-github-artifact-trigger.md
=> fix(pipelines/artifacts): fix github trigger post

.gitignore, _posts/admin/2018-09-18-configure-travis-with-halyard.md
Also added vim swap files to .gitignore.
=> Add KB for configuring Travis w/ Halyard

_includes/document-icon.html, _posts/admin/2018-08-01-Clouddriver-Redis-Migration.md, _sass/tutorials.scss
=> imp: Visual improvement

_posts/admin/2018-10-02-set-execution-history-lookback.md
=> Article about adjusting the execution history

_posts/kubernetes/1200-09-01-K8-general-kubernetes-questions.md
Added all Q&A from the webinar
=> ENG-2730 KB: Update kubernetes page with webinar q&a

_posts/troubleshooting/2018-12-12-default-bake-account.md
document creds not found error and solution
=> docs(credsnotfound): document creds not found

README.md
just testing out PRs and branching - by making some minor changes.
=> fixing some spelling mistakes

_posts/armory/2019-04-01-armory-diagnostics.md
...and document what data is transmitted to Armory when enabled.
=> Document how to enable Armory diagnostics

_posts/aws/2019-05-29-AWS-Lambda-HowTo.md
added a note that this is a proof of concept implementation
=> fix(docs): lambdahowto

_posts/kubernetes/2019-06-14-dynamic-configmap-secret-deployment.md
Example configuration and pipeline design for creating Kubernetes configmaps and secrets out of spinnaker artifact files on the fly.
=> chore(kb): Create k8s configmaps and secrets from artifact files

_posts/admin/2018-05-09-armory-version.md, _posts/admin/2018-12-03-armory-halyard-overview.md, _posts/admin/2018-12-03-armory-halyard-upgrade.md, _posts/aws/1100-09-01-AWS-installing-on-multiple-accounts.1.md, _posts/aws/2018-05-15-AWS-Getting-IP.md, _posts/aws/2018-09-28-target-specific-subnet-during-bake-stage.md, _posts/getting-started-video-series/1000-01-01-spinnaker-concepts.md, _posts/getting-started-video-series/1000-01-01-what-is-spinnaker.md, _posts/pipelines/1000-07-01-script-stage.md
Made minor edits to 8 different KB articles, largely typos / grammar. Can I get some 👀 on this before we merge? Thanks in advance!
=> fix(kb): fixed minor errors and typos in KB articles

_includes/footer.html
Swaps out javascript snippet from intercom to drift 
https://trello.com/c/fCYFLBTN/153-swap-intercom-to-drift-on-both-blog-docs-kb
=> feat(site): Swaps intercom for drift

_posts/releases/1300-09-02-alpha-beta-GA.md, _posts/releases/1300-09-02_alpha_beta_GA.md
Update the KB article to align w/ the Product Release Playbook
=> docs(kb): update release definition kb

_posts/installation/2019-10-22-ssh-keys-in-terraformer.md
docs(terraformer): Adding SSH Keys Guide
Adding a guide for the installation of Terraformer to show how to add SSH Keys.
=> docs(terraformer): Adding SSH Keys Guide

_posts/kubernetes/2020-03-12-upgrade-kustomize.md
Add kb article about How to upgrade the kustomize version
=> docs(kb): add article about how to upgrade the kustomize version

_posts/troubleshooting/2020-05-27-tls-error.md
How to fix TLS error "Reason: extension (5) should not be presented in certificate_request"
=> new(kb): adding kb for tls-error

_posts/kubernetes/2020-05-27-operator-custom-ca.md, _posts/troubleshooting/2020-05-27-tls-error.md
“x509: certificate signed by unknown authority”
=> new(kb): adding instructions for adding custom-ca for operator
